Create DATABASE IF NOT EXISTS name;
use name;

CREATE TABLE ADMIN (
    ID INT NOT NULL AUTO_INCREMENT (5) PRIMARY KEY,
    AdminUSR,
    AdminID,
    AdminPS 
);
-- Admin stuff
-- PS = PASSWORD, ID = ADMIN IDENTIFICAION, USR = USERNAME